### ISSUE TITLE
how to install it

### ISSUE THREAD

**Issue by microspino** [jcollard/elm-audio#5]
Hi, which is the proper way to install **elm-audio** into my elm project? Tried with `elm package install` but no luck. I would like to play some music into a small game :)

**Comment by jcollard** [comment]
Unfortunately, this library is quite old and is not compatible with the latest version of Elm. I'm working on a video series on how to create Tetris in Elm which may result in me rewriting this. However, I would recommend using ports to accomplish this for now.
